// Generated by typings
// Source: https://raw.githubusercontent.com/jstype/typed-npm-http-assert/2bc21f22d4f0de78a2ad19ac5980cf22c6463732/index.d.ts
declare module 'http-assert' {
interface createAssert {
    (value: any, status: number, msg: string, opts?: any): void;
    equal(a: any, b: any, status: number, msg: string, opts?: any): void;
    notEqual(a: any, b: any, status: number, msg: string, opts?: any): void;
    strictEqual(a: any, b: any, status: number, msg: string, opts?: any): void;
    notStrictEqual(a: any, b: any, status: number, msg: string, opts?: any): void;
    deepEqual(a: any, b: any, status: number, msg: string, opts?: any): void;
    notDeepEqual(a: any, b: any, status: number, msg: string, opts?: any): void;
}

const assert: createAssert;

export = assert;
}
